DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS test;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE test (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    student TEXT NOT NULL,
    specialty TEXT NOT NULL
);
